# Generated by Django 3.0.5 on 2020-05-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeritem',
            name='eq_slot',
        ),
    ]
