# Generated by Django 3.0.3 on 2020-05-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_playeritem_eq_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_town',
            field=models.CharField(default='Espin', max_length=100),
        ),
    ]
